// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujatznfjpwdhogtuwctp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqYXR6bmZqcHdkaG9ndHV3Y3RwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4NzQ0MjEsImV4cCI6MjA1ODQ1MDQyMX0.14VV7tnVXWIRJsoaDUVeMhMt7FhvmKoqvBmAG6Y_w3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);